//! On-chain parity: drives `QuayAmm` exactly like Jupiter's resolver would —
//! from nothing but raw account blobs — and asserts `quote()` reproduces what
//! the on-chain program actually paid for every recorded swap.
//!
//! Fixtures live in `fixtures/*.json` and are generated by the litesvm
//! suite (`onchain/tests-litesvm/tests/adapter_fixtures.rs`) by executing
//! real swaps against the compiled program. Each fixture carries the full
//! account set at a snapshot plus `(side, amount_in, actual amount_out)` for
//! an amount sweep on both sides — `out: null` means the on-chain swap
//! FAILED, and the adapter must refuse to quote it (or quote zero output).

#![allow(
    clippy::unwrap_used,
    clippy::expect_used,
    clippy::panic,
    reason = "test code: panic on assertion failure is the desired behavior"
)]

use std::str::FromStr;
use std::sync::atomic::Ordering;

use jupiter_amm_interface::{
    AccountMap, Amm, AmmContext, ClockRef, FeeMode, KeyedAccount, QuoteParams, SwapMode,
};
use quay_aggregator_jupiter::QuayAmm;
use solana_sdk::account::Account;
use solana_sdk::pubkey::Pubkey;

const SIDE_SELL_BASE: u8 = 0;

fn b64_decode(s: &str) -> Vec<u8> {
    use base64::Engine as _;
    base64::engine::general_purpose::STANDARD
        .decode(s)
        .expect("valid base64 in fixture")
}

struct Fixture {
    strategy: Pubkey,
    base_mint: Pubkey,
    quote_mint: Pubkey,
    clock_slot: u64,
    clock_unix_ts: i64,
    accounts: Vec<(Pubkey, Account)>,
    /// `(side, amount_in, Some(actual_out) | None-if-on-chain-failed)`
    swaps: Vec<(u8, u64, Option<u64>)>,
}

fn load_fixture(name: &str) -> Fixture {
    let path = format!("{}/fixtures/{name}.json", env!("CARGO_MANIFEST_DIR"));
    let raw = std::fs::read_to_string(&path)
        .unwrap_or_else(|e| panic!("read fixture {path}: {e} — regenerate with the litesvm suite"));
    let v: serde_json::Value = serde_json::from_str(&raw).expect("valid fixture JSON");

    let pk = |field: &str| Pubkey::from_str(v[field].as_str().expect(field)).expect(field);
    let accounts = v["accounts"]
        .as_array()
        .expect("accounts array")
        .iter()
        .map(|a| {
            let key = Pubkey::from_str(a["pubkey"].as_str().expect("pubkey")).expect("pubkey");
            let account = Account {
                lamports: a["lamports"].as_u64().expect("lamports"),
                data: b64_decode(a["data_b64"].as_str().expect("data_b64")),
                owner: Pubkey::from_str(a["owner"].as_str().expect("owner")).expect("owner"),
                executable: false,
                rent_epoch: 0,
            };
            (key, account)
        })
        .collect();
    let swaps = v["swaps"]
        .as_array()
        .expect("swaps array")
        .iter()
        .map(|s| {
            (
                s["side"].as_u64().expect("side") as u8,
                s["amount_in"].as_u64().expect("amount_in"),
                s["out"].as_u64(),
            )
        })
        .collect();

    Fixture {
        strategy: pk("strategy"),
        base_mint: pk("base_mint"),
        quote_mint: pk("quote_mint"),
        clock_slot: v["clock_slot"].as_u64().expect("clock_slot"),
        clock_unix_ts: v["clock_unix_ts"].as_i64().expect("clock_unix_ts"),
        accounts,
        swaps,
    }
}

/// Full integrator flow for one fixture: construct from the raw strategy
/// account, `update()` from the fixture's account set, then `quote()` every
/// recorded swap and compare against the on-chain truth.
fn assert_parity(name: &str) {
    let f = load_fixture(name);
    let account_of = |k: &Pubkey| -> Account {
        f.accounts
            .iter()
            .find(|(key, _)| key == k)
            .unwrap_or_else(|| panic!("fixture {name} missing account {k}"))
            .1
            .clone()
    };

    let clock_ref = ClockRef::default();
    clock_ref.slot.store(f.clock_slot, Ordering::Relaxed);
    clock_ref
        .unix_timestamp
        .store(f.clock_unix_ts, Ordering::Relaxed);
    let ctx = AmmContext { clock_ref };

    let keyed = KeyedAccount {
        key: f.strategy,
        account: account_of(&f.strategy),
        params: None,
    };
    let mut amm = QuayAmm::from_keyed_account(&keyed, &ctx).expect("from_keyed_account");

    // Every account the adapter wants must be in the fixture — otherwise the
    // generator's account list has drifted from the adapter's.
    let mut map = AccountMap::default();
    for k in amm.get_accounts_to_update() {
        map.insert(k, account_of(&k));
    }
    amm.update(&map).expect("update");
    assert!(
        amm.is_active(),
        "fixture {name}: venue inactive after update"
    );

    for (side, amount_in, expected_out) in &f.swaps {
        let (input_mint, output_mint) = if *side == SIDE_SELL_BASE {
            (f.base_mint, f.quote_mint)
        } else {
            (f.quote_mint, f.base_mint)
        };
        let quote = amm.quote(&QuoteParams {
            amount: *amount_in,
            input_mint,
            output_mint,
            swap_mode: SwapMode::ExactIn,
            // Jupiter platform-fee mode; Quay's pricing doesn't depend on it.
            fee_mode: FeeMode::default(),
        });

        match expected_out {
            Some(out) => {
                let q = quote.unwrap_or_else(|e| {
                    panic!(
                        "fixture {name}: on-chain swap (side {side}, in {amount_in}) paid {out} \
                         but the adapter refused to quote it: {e}"
                    )
                });
                assert_eq!(
                    q.out_amount, *out,
                    "fixture {name}: side {side}, in {amount_in} — adapter quoted \
                     {} but the program paid {out}",
                    q.out_amount
                );
                assert_eq!(
                    q.in_amount, *amount_in,
                    "fixture {name}: in_amount mismatch"
                );
            }
            None => {
                if let Ok(q) = quote {
                    assert_eq!(
                        q.out_amount, 0,
                        "fixture {name}: side {side}, in {amount_in} FAILED on-chain but the \
                         adapter quoted out {} — routers would build doomed transactions",
                        q.out_amount
                    );
                }
            }
        }
    }
}

/// A missing or truncated mint account must fail `update()` — quoting with
/// stale decimals or a wrong token program mis-prices the venue.
#[test]
fn update_rejects_missing_or_truncated_mint() {
    let f = load_fixture("flat");
    let account_of = |k: &Pubkey| -> Account {
        f.accounts
            .iter()
            .find(|(key, _)| key == k)
            .unwrap_or_else(|| panic!("fixture flat missing account {k}"))
            .1
            .clone()
    };

    let ctx = AmmContext {
        clock_ref: ClockRef::default(),
    };
    let keyed = KeyedAccount {
        key: f.strategy,
        account: account_of(&f.strategy),
        params: None,
    };
    let mut amm = QuayAmm::from_keyed_account(&keyed, &ctx).expect("from_keyed_account");

    let mut map = AccountMap::default();
    for k in amm.get_accounts_to_update() {
        map.insert(k, account_of(&k));
    }

    let mut missing = map.clone();
    missing.remove(&f.base_mint);
    assert!(
        amm.update(&missing).is_err(),
        "missing base mint must fail update"
    );
    // `update()` commits atomically: the failed update above must not have
    // half-applied the fixture's cleared halt bytes — the warmup lock
    // (halt defaults from `from_keyed_account`) still holds.
    assert!(
        !amm.is_active(),
        "failed first update must leave the venue inactive"
    );

    let mut truncated = map.clone();
    truncated.get_mut(&f.quote_mint).unwrap().data.truncate(10);
    assert!(
        amm.update(&truncated).is_err(),
        "truncated quote mint must fail update"
    );
    assert!(
        !amm.is_active(),
        "failed update must leave the venue inactive"
    );

    // The intact map still updates fine afterwards.
    amm.update(&map).expect("update with full map");
    assert!(amm.is_active(), "venue active after recovering update");
}

#[test]
fn parity_flat() {
    assert_parity("flat");
}

#[test]
fn parity_spread_fee() {
    assert_parity("spread_fee");
}

#[test]
fn parity_exact_fee() {
    assert_parity("exact_fee");
}

#[test]
fn parity_one_sided() {
    assert_parity("one_sided");
}
